name: GitHub Actions
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing current branch
        run: dotnet test
      - name: switch to main branch
        uses: Radon-Rodion/ITechArtLabDotNet@main
      - name: testing main branch
        run: dotnet test